#!/usr/bin/env python3

import argparse
import os
import subprocess

from infra import switch_context

services = ["device"]


def deploy_service(environment, service_name):
    if service_name not in services:
        raise ValueError(f"Unknown service_name: {service_name}")

    script_directory = os.path.dirname(os.path.abspath(__file__))
    base_path = os.path.join(script_directory, "kustomize")
    source_path = os.path.join(base_path, f"overlays/{environment}/{service_name}")

    command = f"kubectl apply -k {source_path}"
    subprocess.run(command, shell=True, cwd=base_path, check=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Deploy a service to a specified environment"
    )
    parser.add_argument(
        "-e", "--environment", help="The environment to deploy to", required=True
    )
    parser.add_argument("-s", "--service", help="The service to deploy", required=True)

    args = parser.parse_args()

    switch_context(args.environment)
    deploy_service(args.environment, args.service)
