repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts

packages:
  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: monitoring
    values: packages/metrics-server/values.yaml
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: monitoring
  - name: mosquitto
    chart: k8s-at-home/mosquitto
    namespace: iot
    values: packages/mosquitto/values.yaml
