#!/usr/bin/env python3

import subprocess
import sys
from infra import switch_context


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python set-context.py <context_name>")
        sys.exit(1)

    environment = sys.argv[1]
    switch_context(environment)
