apiVersion: v1
kind: Service
metadata:
    name: device-service
    namespace: iot
    labels:
        app: device
spec:
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    selector:
        app: device
    type: ClusterIP
